# Generated by Django 4.2.7 on 2023-12-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('instrument_type', models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Violin', 'Violin'), ('Cello', 'Cello'), ('Brass instrument', 'Brass instrument')], max_length=100)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician_app.musician')),
            ],
        ),
    ]
