# Generated by Django 4.2.7 on 2023-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
